kind: pipeline
type: docker
name: humans-docs

steps:
  - name: build and publish image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.humans.ai
      repo: registry.humans.ai/docs
      tags: latest
